# Generated by Django 5.0 on 2024-01-02 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contentApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acmarapor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Veri Giren'),
        ),
        migrations.AddField(
            model_name='acmarapor',
            name='placebuluntu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentApp.buluntuyeri', verbose_name='Buluntu Yeri'),
        ),
        migrations.AddField(
            model_name='documentcreatemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Formu Dolduran'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='taxrate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentApp.customtaxrate', verbose_name='Vergi'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='typeofaddition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentApp.fixturegaintype', verbose_name='Alış Şekli'),
        ),
        migrations.AddField(
            model_name='setgeneralbuluntu',
            name='area',
            field=models.ManyToManyField(to='contentApp.buluntualani', verbose_name='Buluntu / Kova Alanı'),
        ),
        migrations.AddField(
            model_name='setgeneralbuluntu',
            name='colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentApp.setcolour', to_field='color', verbose_name='Buluntu Renk'),
        ),
        migrations.AddField(
            model_name='setgeneralbuluntu',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentApp.buluntuperiod', verbose_name='Dönem'),
        ),
        migrations.AddField(
            model_name='setgeneralbuluntu',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentApp.buluntutypes', to_field='buluntu', verbose_name='Tür'),
        ),
        migrations.AddField(
            model_name='setgeneralbuluntu',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='generalinstructions',
            name='buluntu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contentApp.setgeneralbuluntu', verbose_name='Buluntu'),
        ),
        migrations.AddField(
            model_name='buluntuimages',
            name='buluntu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contentApp.setgeneralbuluntu', verbose_name='Buluntu'),
        ),
    ]
