# Generated by Django 5.0 on 2023-12-14 16:13

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuluntuYeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Buluntu Yeri')),
            ],
        ),
        migrations.CreateModel(
            name='AcmaRapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily', models.BooleanField(default=False, verbose_name='Günlük')),
                ('weekly', models.BooleanField(default=False, verbose_name='Haftalık')),
                ('fifteenday', models.BooleanField(default=False, verbose_name='15 Günlük')),
                ('monthly', models.BooleanField(default=True, verbose_name='Aylık')),
                ('closing', models.BooleanField(default=True, verbose_name='Kapanış')),
                ('rapordate', models.DateField(verbose_name='Rapor Tarihi')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('owner', models.CharField(max_length=150, verbose_name='Formu Dolduran')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Veri Giren')),
                ('placebuluntu', models.ManyToManyField(to='contentApp.buluntuyeri', verbose_name='Buluntu Yeri')),
            ],
        ),
        migrations.CreateModel(
            name='AcmaRaporDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapordetail', ckeditor.fields.RichTextField(verbose_name='Rapor Detay')),
                ('rapor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contentApp.acmarapor', verbose_name='Acma Rapor')),
            ],
        ),
        migrations.CreateModel(
            name='AcmaRaporFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='raporfiles', verbose_name='Evrak Yükleme')),
                ('rapor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contentApp.acmarapor', verbose_name='Acma Rapor')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCreateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomingdoc', models.BooleanField(default=False, verbose_name='Gelen Evrak')),
                ('outgoingdoc', models.BooleanField(default=False, verbose_name='Giden Evrak')),
                ('amount', models.BooleanField(default=False, verbose_name='Tutanak')),
                ('high', models.BooleanField(default=False, verbose_name='Yüksek')),
                ('middle', models.BooleanField(default=False, verbose_name='Orta')),
                ('low', models.BooleanField(default=False, verbose_name='Düşük')),
                ('docno', models.CharField(max_length=150, verbose_name='Evrak No')),
                ('docdate', models.DateField(verbose_name='Evrak Tarihi')),
                ('doccount', models.IntegerField(verbose_name='Evrak Sayisi')),
                ('relevantunit', models.CharField(max_length=150, verbose_name='İlgili Birim')),
                ('relevantinstitution', models.CharField(max_length=150, verbose_name='İlgili Kurum')),
                ('docsubject', models.CharField(max_length=150, verbose_name='Evrak Konusu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Formu Dolduran')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='document', verbose_name='Evrak Yükleme')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contentApp.documentcreatemodel', verbose_name='İlgili Döküman')),
            ],
        ),
        migrations.CreateModel(
            name='RaporDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', ckeditor.fields.RichTextField(verbose_name='Rapor Detay')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contentApp.documentcreatemodel', verbose_name='İlgili Döküman')),
            ],
        ),
    ]
