# Generated by Django 4.2.7 on 2024-01-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuluntuYeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Buluntu Yeri')),
            ],
        ),
        migrations.CreateModel(
            name='AcmaRapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapor_type', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('fifteenday', '15 Günlük'), ('monthly', 'Aylık'), ('closing', 'Kapanış')], default='daily', max_length=10, verbose_name='Rapor Tipi')),
                ('rapordate', models.DateField(verbose_name='Rapor Tarihi')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('owner', models.CharField(max_length=150, verbose_name='Formu Dolduran')),
                ('rapordetail', models.TextField(verbose_name='Rapor Detay')),
                ('file', models.FileField(upload_to='raporfiles', verbose_name='Evrak Yükleme')),
                ('placebuluntu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapor.buluntuyeri', verbose_name='Buluntu Yeri')),
            ],
        ),
    ]
