# Generated by Django 4.2.7 on 2024-01-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Verginin Adı')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Vergi Oranı')),
            ],
        ),
        migrations.CreateModel(
            name='FixtureGainType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=50, verbose_name='Alış Type')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Demirbaş Adı')),
                ('marka', models.CharField(max_length=150, verbose_name='Marka')),
                ('model', models.CharField(max_length=150, verbose_name='Model')),
                ('piece', models.IntegerField(verbose_name='Adet')),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Birim Fiyatı')),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Toplam Fiyat')),
                ('dateofaddition', models.DateField(verbose_name='Alım Tarihi')),
                ('where', models.CharField(max_length=150, verbose_name='Bulunduğu Yer')),
                ('custodian', models.CharField(max_length=150, verbose_name='Zimmetli Kişi')),
                ('barcode', models.CharField(max_length=150, verbose_name='Barkod Numarası')),
                ('companyName', models.CharField(max_length=150, verbose_name='Firma Adı')),
                ('companyOfficial', models.CharField(max_length=150, verbose_name='Firma Yetkilisi')),
                ('companyPhone', models.CharField(max_length=150, verbose_name='Firma Telefon')),
                ('companyEmail', models.EmailField(max_length=254, verbose_name='Firma E-Mail')),
                ('companyAddress', models.TextField(verbose_name='Firma Adresi')),
                ('fixtureFile', models.FileField(upload_to='fixture', verbose_name='Demirbaş Alım Belgesi')),
                ('fixtureDescription', models.TextField(max_length=900, verbose_name='Demirbaş Açıklama')),
                ('taxrate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixture.customtaxrate', verbose_name='Vergi')),
                ('typeofaddition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixture.fixturegaintype', verbose_name='Alış Şekli')),
            ],
        ),
    ]
