# Generated by Django 4.2.7 on 2024-01-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCreateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomingdoc', models.BooleanField(default=False, verbose_name='Gelen Evrak')),
                ('outgoingdoc', models.BooleanField(default=False, verbose_name='Giden Evrak')),
                ('amount', models.BooleanField(default=False, verbose_name='Tutanak')),
                ('high', models.BooleanField(default=False, verbose_name='Yüksek')),
                ('middle', models.BooleanField(default=False, verbose_name='Orta')),
                ('low', models.BooleanField(default=False, verbose_name='Düşük')),
                ('docno', models.CharField(max_length=150, verbose_name='Evrak No')),
                ('docdate', models.DateField(verbose_name='Evrak Tarihi')),
                ('doccount', models.IntegerField(verbose_name='Evrak Sayisi')),
                ('relevantunit', models.CharField(max_length=150, verbose_name='İlgili Birim')),
                ('relevantinstitution', models.CharField(max_length=150, verbose_name='İlgili Kurum')),
                ('docsubject', models.CharField(max_length=150, verbose_name='Evrak Konusu')),
                ('files', models.FileField(upload_to='document', verbose_name='Evrak Yükleme')),
                ('detail', models.TextField(verbose_name='Rapor Detay')),
            ],
        ),
    ]
