# Generated by Django 4.2.7 on 2024-01-14 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buluntu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setgeneralbuluntu',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='minorbuluntuform',
            name='bezeme',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buluntu.bezeme', verbose_name='Bezeme'),
        ),
        migrations.AddField(
            model_name='minorbuluntuform',
            name='color',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buluntu.astarcolour', verbose_name='Renkler'),
        ),
        migrations.AddField(
            model_name='minorbuluntuform',
            name='hamurBoy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buluntu.hamurkatkiboy', verbose_name='Katkı Boyutu'),
        ),
        migrations.AddField(
            model_name='minorbuluntuform',
            name='hamurFirinlama',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buluntu.hamurfirinlama', verbose_name='Fırınlama'),
        ),
        migrations.AddField(
            model_name='minorbuluntuform',
            name='hamurGozeneklik',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buluntu.hamurgozeneklilik', verbose_name='Gözeneklilik'),
        ),
        migrations.AddField(
            model_name='minorbuluntuform',
            name='hamurSertlik',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buluntu.hamursertlik', verbose_name='Sertlik'),
        ),
        migrations.AddField(
            model_name='minorbuluntuform',
            name='hamurTur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buluntu.hamurkatkitur', verbose_name='Katkı Türü'),
        ),
        migrations.AddField(
            model_name='minorbuluntuform',
            name='hamurYuzey',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buluntu.hamuryuzey', verbose_name='Hamur Yüzey Uygulamaları'),
        ),
        migrations.AddField(
            model_name='minorbuluntuform',
            name='piece',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='eserler', to='buluntu.pieces', verbose_name='Eser'),
        ),
        migrations.AddField(
            model_name='minorbuluntu',
            name='form',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buluntu.minorbuluntuform', verbose_name='Küçük Buluntu Formu'),
        ),
        migrations.AddField(
            model_name='generalinstructions',
            name='buluntu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buluntu.setgeneralbuluntu', verbose_name='Buluntu'),
        ),
        migrations.AddField(
            model_name='buluntuimages',
            name='buluntu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buluntu.setgeneralbuluntu', verbose_name='Buluntu'),
        ),
    ]
